module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      purple: "#3f3cbb",
      midnight: "#121063",
      metal: "#565584",
      tahiti: "#3ab7bf",
      silver: "#ecebff",
      "bubble-gum": "#ff77e9",
      bermuda: "#78dcca",
      header: "#131921",
      search: "#ebb475",
      headersecond: "#232f3e",
      background: "#eaeded",
      black: "#000000",
      button: "#ff9900",
    },
  },
  plugins: [],
};
